import { Product, Testimonial } from "./types";

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Premium Detox Mix",
    description: "Our signature blend of triple-filtered herbs for a deep cellular cleanse.",
    price: 349,
    image: "/input_file_1.png",
    category: "Detox",
    featured: true,
  },
  {
    id: "2",
    name: "Classic Digestion Mix",
    description: "The time-tested formula for optimal digestive harmony and comfort.",
    price: 199,
    image: "/input_file_1.png",
    category: "Wellness",
    featured: true,
  },
  {
    id: "3",
    name: "Energy Boost Mix",
    description: "Revitalize your body with natural stimulants and adaptogens.",
    price: 299,
    image: "/input_file_1.png",
    category: "Energy",
    featured: true,
  },
  {
    id: "4",
    name: "Detox Basic",
    description: "A gentle daily detox blend for beginners starting their wellness journey.",
    price: 249,
    image: "/input_file_2.png",
    category: "Detox",
  },
  {
    id: "5",
    name: "Slim Fit Premium",
    description: "Advanced metabolism support with natural fat-burning botanical extracts.",
    price: 599,
    image: "/input_file_1.png",
    category: "Wellness",
    featured: true,
  },
  {
    id: "6",
    name: "Immunity Basic",
    description: "Daily support for your immune system with essential natural herbs.",
    price: 229,
    image: "https://images.unsplash.com/photo-1517849845537-4d257902454a?q=80&w=800&auto=format&fit=crop",
    category: "Wellness",
  },
  {
    id: "7",
    name: "Jaljeera Mix",
    description: "Refreshing and tangy traditional Indian digestive cooler.",
    price: 149,
    image: "https://images.unsplash.com/photo-1547514701-42782101795e?q=80&w=800&auto=format&fit=crop",
    category: "Hydration",
    featured: true,
  },
  {
    id: "8",
    name: "Liver Detox Mix",
    description: "Targeted support for liver health and natural toxin processing.",
    price: 399,
    image: "/input_file_1.png",
    category: "Detox",
  },
  {
    id: "9",
    name: "Strong Digestion Mix",
    description: "Our most potent formula for those requiring extra digestive support.",
    price: 299,
    image: "https://images.unsplash.com/photo-1512211534344-9388f8da988b?q=80&w=800&auto=format&fit=crop",
    category: "Wellness",
  },
  {
    id: "10",
    name: "Fat Burn Mix",
    description: "Thermogenic herb blend to support active weight loss goals.",
    price: 449,
    image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?q=80&w=800&auto=format&fit=crop",
    category: "Wellness",
  },
  {
    id: "11",
    name: "Kadha Mix Strong",
    description: "Traditional Ayurvedic decoction for respiratory health and immunity.",
    price: 279,
    image: "https://images.unsplash.com/photo-1585244799493-40af3667936a?q=80&w=800&auto=format&fit=crop",
    category: "Wellness",
  },
  {
    id: "12",
    name: "Morning Energy Drink",
    description: "The perfect caffeine-free start to your morning for sustained energy.",
    price: 249,
    image: "https://images.unsplash.com/photo-1544145945-f904253db0ad?q=80&w=800&auto=format&fit=crop",
    category: "Energy",
  },
  {
    id: "13",
    name: "Omega Health Mix",
    description: "Natural source of vital fatty acids from plant-based superfoods.",
    price: 499,
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=800&auto=format&fit=crop",
    category: "Wellness",
  },
  {
    id: "14",
    name: "Sugar Control Mix",
    description: "Herbal blend to help maintain healthy blood sugar levels naturally.",
    price: 399,
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?q=80&w=800&auto=format&fit=crop",
    category: "Wellness",
  },
  {
    id: "15",
    name: "Instant Gas Relief",
    description: "Fast-acting carminative herbs for immediate bloating relief.",
    price: 199,
    image: "https://images.unsplash.com/photo-1512211534344-9388f8da988b?q=80&w=800&auto=format&fit=crop",
    category: "Wellness",
  },
  {
    id: "16",
    name: "ACV Detox Drink",
    description: "Apple Cider Vinegar powered blend for metabolism and detox.",
    price: 349,
    image: "/input_file_1.png",
    category: "Detox",
  },
  {
    id: "17",
    name: "Green Detox Tea",
    description: "Antioxidant-rich green tea leaves with purifying herbal infusions.",
    price: 299,
    image: "/input_file_2.png",
    category: "Detox",
  },
  {
    id: "18",
    name: "Throat Care Mix",
    description: "Soothing herbs like Mulethi and Ginger for respiratory comfort.",
    price: 179,
    image: "/input_file_1.png",
    category: "Wellness",
  },
  {
    id: "19",
    name: "Daily Immunity Mix",
    description: "Your everyday shield fortified with Ashwagandha and Giloy.",
    price: 329,
    image: "/input_file_2.png",
    category: "Wellness",
  },
  {
    id: "20",
    name: "Mint Cooler",
    description: "Ice-cold sensation from fresh peppermint and mountain herbs.",
    price: 129,
    image: "/input_file_1.png",
    category: "Hydration",
  },
  {
    id: "21",
    name: "Natural Electrolyte Mix",
    description: "Mineral-rich herbs for perfect hydration after physical activity.",
    price: 199,
    image: "/input_file_2.png",
    category: "Hydration",
  },
  {
    id: "22",
    name: "Stress Relief Mix",
    description: "Calm your mind and soothe nerves with neural-relaxing herbs.",
    price: 429,
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=800&auto=format&fit=crop",
    category: "Wellness",
  },
  {
    id: "23",
    name: "Cooling Digest Mix",
    description: "Combines digestive support with a unique temperature-lowering effect.",
    price: 259,
    image: "https://images.unsplash.com/photo-1547514701-42782101795e?q=80&w=800&auto=format&fit=crop",
    category: "Wellness",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "1",
    name: "Anita Sharma",
    comment: "The Detox Mix actually works! I feel so much lighter and more energetic throughout the day.",
    rating: 5,
  },
  {
    id: "2",
    name: "Vikram Mehta",
    comment: "The best herbal site I've found. Shipping was fast and the packaging is very premium.",
    rating: 4,
  },
  {
    id: "3",
    name: "Sneha Kapoor",
    comment: "I love the cooling drink. It's my go-to after workouts. Total value for money.",
    rating: 5,
  },
];

export const HERO_SLIDES = [
  {
    id: 1,
    title: "Climjo",
    subtitle: "Clean Living + Joy • Natural. Pure. You. Experience the magic of herbal living.",
    offer: "Premium Wellness",
    image: "/input_file_2.png",
  },
  {
    id: 2,
    title: "Refresh Your System",
    subtitle: "Pure herbal extracts designed for the ultimate natural cleanse.",
    offer: "Flat 20% Off",
    image: "/input_file_1.png",
  },
  {
    id: 3,
    title: "The Natural Choice",
    subtitle: "Ditch the chemicals. Embrace the joy of clean, herbal living.",
    offer: "Free Shipping on ₹999+",
    image: "/input_file_0.png",
  },
];
